<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tours</title>

    <link rel="shortcut icon" href="img/icono.png" type="image/x-icon">
    <link rel="stylesheet" href="css/tour.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
</head>
<body>
<header>
        <nav>
            <a href="/index">Inicio</a>
            <a href="/alojamientos">Alojamiento</a>
            <a href="/recorridos">Recorrido</a>
            <a href="/Tours">Tours</a>
            <a href="/Contacto">Contacto</a>
        </nav>

        <section class="textos-header">
        
        <h1>
            Encuentra tus próximas vacaciones
        </h1>

        <h2>
            Con turismo.loc
        </h2>

        <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->

        <div class = "wave" style="height: 150px; overflow: hidden;" ><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;"><path d="M0.00,49.98 C149.99,150.00 349.20,-49.98 500.00,49.98 L500.00,150.00 L0.00,150.00 Z" style="stroke: none; fill: #fff;"></path></svg></div>
        
        </section>

    </header>

    <main>
        <section class="contedor tours">
            <h2 class="titulo">
                Aquí podrás encontrar nuestra selección de Tours
            </h2>

            <div class="contenedor-tours">
                <img src="img/peñol.jpg" alt="" class = "img-port-recor">
                <div class="contenedor-textrecor">
                    <h2>
                        Caracteristicas de nuestros Tours
                    </h2>

                    <h3><span></span> Esta es una caracteristica del Tours.</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae ea voluptatibus odio architecto voluptate soluta itaque ipsam in sequi fuga ad, ipsa beatae esse numquam illo veritatis illum ab ex!</p>
                    <h3><span></span> Esta es una caracteristica del Tours.</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae ea voluptatibus odio architecto voluptate soluta itaque ipsam in sequi fuga ad, ipsa beatae esse numquam illo veritatis illum ab ex!</p>
                    <h3><span></span> Esta es una caracteristica del Tours.</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae ea voluptatibus odio architecto voluptate soluta itaque ipsam in sequi fuga ad, ipsa beatae esse numquam illo veritatis illum ab ex!</p>
                    <h3><span></span> Esta es una caracteristica del Tours.</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae ea voluptatibus odio architecto voluptate soluta itaque ipsam in sequi fuga ad, ipsa beatae esse numquam illo veritatis illum ab ex!</p>
                    <h3><span></span> Esta es una caracteristica del Tours.</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae ea voluptatibus odio architecto voluptate soluta itaque ipsam in sequi fuga ad, ipsa beatae esse numquam illo veritatis illum ab ex!</p>
                 </div>
                </div>
            </section>

            <section class="acerca-tour">
            <div class="contenedor tour">
                <h2 class="titulo">Nuestros Tours</h2>
                <div class="servicio-cont">
                    <div class="servi_indi">
                        <img src="img/tour1.jpg" alt="">
                        <h3>El Peñol</h3>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, alias!</p>
                        <a href="/tour_peñol"><button type="button">Reserbame</button></a>
                    </div>
                    <div class="servi_indi">
                        <img src="img/tour2.jpg" alt="">
                        <h3>Graffiti - Comuna 13</h3>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, alias!</p>
                        <a href="/tour_graffiti"><button type="button">Reserbame</button></a>
                    </div>
                    <div class="servi_indi">
                        <img src="img/tour3R.jpg" alt="">
                        <h3>Isla Rosario</h3>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, alias!</p>
                        <a href="/tour_rosario"><button type="button">Reserbame</button></a>
                    </div>
                    
                   
                </div>
            </div>
        </section> 
    </main>
    <footer>
        <div class="contenedor-footer">
            <div class="content-foot">
                <h4>Teléfono</h4>
                <p>1234567890</p>
            </div>
            <div class="content-foot">
                <h4>Email</h4>
                <p>Correo@deprueba.com</p>
            </div>
            <div class="content-foot">
                <h4>Dirección</h4>
                <p>Calle falsa # 1-23</p>
            </div>
        </div>
        <h2 class="titulo-final">&copy; Takeomatsu's Art | Santiago Bravo</h2>
    </footer>
</body>
</html>