<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Turismo</title>
    <link rel="shortcut icon" href="img/icono.png" type="image/x-icon">
    <link rel="stylesheet" href="css/index.css">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans&display=swap" rel="stylesheet">
</head>
<body>
    <header>
        <nav>
            <a href="/index">Inicio</a>
            <a href="/alojamientos">Alojamiento</a>
            <a href="/recorridos">Recorrido</a>
            <a href="/Tours">Tours</a>
            <a href="/Contacto">Contacto</a>
        </nav>

        <section class="textos-header">
        
        <h1>
            Encuentra tus próximas vacaciones
        </h1>

        <h2>
            Con turismo.loc
        </h2>

        <!-- Generated by https://smooth.ie/blogs/news/svg-wavey-transitions-between-sections -->

        <div class = "wave" style="height: 150px; overflow: hidden;" ><svg viewBox="0 0 500 150" preserveAspectRatio="none" style="height: 100%; width: 100%;"><path d="M0.00,49.98 C149.99,150.00 349.20,-49.98 500.00,49.98 L500.00,150.00 L0.00,150.00 Z" style="stroke: none; fill: #fff;"></path></svg></div>
        
        </section>

    </header>

    <main>
    
        <section class="contenedor productos">
        
           <h2 class="titulo">
                Nuestras opciones
           </h2>

            <div class="contenedor_productos">
                <img src="img/principal_opt.jpg" alt="" class = "imagen-alojamiento">
                <div class="contenedor-texto_alojamiento">
                    <h3><span>1</span> Aquí podrás encontrar información acerca de nuestros alojamientos y sus costos.</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae ea voluptatibus odio architecto voluptate soluta itaque ipsam in sequi fuga ad, ipsa beatae esse numquam illo veritatis illum ab ex!</p>
                    <h3><span>2</span> Aquí podrás encontrar información acerca de nuestros recorridos y sus costos.</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae ea voluptatibus odio architecto voluptate soluta itaque ipsam in sequi fuga ad, ipsa beatae esse numquam illo veritatis illum ab ex!</p>
                    <h3><span>3</span> Aquí podrás encontrar información acerca de nuestros tours y nuestros costos.</h3>
                    <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Vitae ea voluptatibus odio architecto voluptate soluta itaque ipsam in sequi fuga ad, ipsa beatae esse numquam illo veritatis illum ab ex!</p>
                </div>
            </div>
            
        </section>

        <section class="portafolio">
            <div class="contenedor">
                <h2 class="titulo">
                    Portafolio
                </h2>

                <div class="galeria-portafolio">
                    <div class="imagen-port">
                    <div class="hover_gal">
                            <img src="img/aprovechar.png" alt="" />
                            <p><a href="/alojamientos"> Nuestros alojamientos</a></p>
                        </div>
                        <img src="img/alojamiento1.jpg" alt="">
                    </div>
                    <div class="imagen-port">
                        <img src="img/recorrido.jpg" alt="">
                            <div class="hover_gal">
                                <img src="img/aprovechar.png" alt="">
                                <p><a href="/alojamientos"> Nuestros recorridos</a></p>
                        </div>
                    </div>
                    <div class="imagen-port">
                        <img src="img/Tours_opt.jpg" alt="700">
                        <div class="hover_gal">
                            <img src="img/aprovechar.png" alt="">
                            <p><a href="/alojamientos"> Nuestros tours</a></p>
                        </div>
                    </div>
                    <div class="imagen-port">
                        <img src="img/contact-us.jpg" alt="">
                        <div class="hover_gal">
                        <img src="img/aprovechar.png" alt="">
                        <p><a href="/alojamientos">Contacta con nosotros</p></a>
                        </div>
                    </div>
                </div>
            </div> 
        </section>

        <section class="clientes contenedor">
            <h2 class="titulo">
                Reseñas de nuetsros clientes
            </h2>
            <div class="cards">
                    <div class="card">
                        <img src="img/cliente1.jpg" alt="">
                        <div class="contenido_textcard1">
                            <h4>Nombre</h4>
                            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ex, iusto.</p>
                        </div>
                    </div>
                    <div class="card">
                        <img src="img/cliente2.jpg" alt="">
                        <div class="contenido_textcard1">
                            <h4>Nombre</h4>
                            <p>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Ex, iusto.</p>
                        </div>
                    </div>
                </div>
        </section>

        <section class="acerc_servi">
            <div class="contenedor servi">
                <h2 class="titulo">Nuestros servicios adicionales</h2>
                <div class="servicio-cont">
                    <div class="servi_indi">
                        <img src="img/simcard.jpg" alt="">
                        <h3>Nombre</h3>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, alias!</p>
                    </div>
                    <div class="servi_indi">
                        <img src="img/transporte .jpg" alt="">
                        <h3>Nombre</h3>
                        <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Soluta, alias!</p>
                    </div>
                </div>
            </div>
        </section> 
    </main>
    <footer>
        <div class="contenedor-footer">
            <div class="content-foot">
                <h4>Teléfono</h4>
                <p>1234567890</p>
            </div>
            <div class="content-foot">
                <h4>Email</h4>
                <p>Correo@deprueba.com</p>
            </div>
            <div class="content-foot">
                <h4>Dirección</h4>
                <p>Calle falsa # 1-23</p>
            </div>
        </div>
        <h2 class="titulo-final">&copy; Takeomatsu's Art | Santiago Bravo</h2>
    </footer>
</body>
</html>